definitions:
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResponse:
    properties:
      token:
        type: string
      username:
        type: string
    type: object
  model.MediaResponse:
    properties:
      id:
        type: integer
    type: object
  model.NotesRequest:
    properties:
      body:
        type: string
      secret:
        type: string
      title:
        type: string
      type:
        type: string
    required:
    - body
    - title
    - type
    type: object
  model.NotesResponse:
    properties:
      body:
        type: string
      id:
        type: integer
      secret:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  model.UserRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      photo:
        type: string
      username:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - username
    type: object
  model.UserResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      id_user:
        type: integer
      last_name:
        type: string
      password:
        type: string
      photo:
        type: string
      role:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/notes/{id}:
    put:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: id notes
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ReActive Notes
      tags:
      - admin
  /login:
    post:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: body request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
      summary: Login User
      tags:
      - login
  /media:
    post:
      consumes:
      - image/jpeg
      description: TODO
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MediaResponse'
      summary: upload media
      tags:
      - media
  /media/{id}:
    get:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: id media
        in: path
        name: id
        required: true
        type: integer
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: download media
      tags:
      - media
  /notes:
    get:
      consumes:
      - application/json
      description: TODO
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.NotesResponse'
            type: array
      summary: Get List Notes
      tags:
      - notes
    post:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: body request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.NotesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.NotesResponse'
      summary: Create Notes
      tags:
      - notes
  /notes/{id}:
    get:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: id notes
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.NotesResponse'
      summary: Get Notes Detail
      tags:
      - notes
    put:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: id notes
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.NotesResponse'
      summary: Update Notes
      tags:
      - notes
  /registrasi:
    post:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: body request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponse'
      summary: Create User
      tags:
      - registrasi
  /verification:
    post:
      consumes:
      - application/json
      description: TODO
      parameters:
      - description: body request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: verified verification code
      tags:
      - registrasi
swagger: "2.0"
